TRUNCATE table customer cascade;
insert into customer (id, first_name, last_name, email, address, phone) values (1, 'Candide', 'Kleis', 'ckleis0@bbb.org', '13th Floor', '875-516-9813');
insert into customer (id, first_name, last_name, email, address, phone) values (2, 'Calv', 'Menary', 'cmenary1@hud.gov', 'Room 120', '979-721-7820');
insert into customer (id, first_name, last_name, email, address, phone) values (3, 'Arri', 'Greser', 'agreser2@biglobe.ne.jp', 'Suite 21', '228-619-9962');
insert into customer (id, first_name, last_name, email, address, phone) values (4, 'Malvina', 'Hawson', 'mhawson3@marketwatch.com', 'PO Box 78229', '831-830-2292');
insert into customer (id, first_name, last_name, email, address, phone) values (5, 'Horatio', 'Wraith', 'hwraith4@homestead.com', 'Apt 242', '764-820-0225');
insert into customer (id, first_name, last_name, email, address, phone) values (6, 'Crissy', 'Simson', 'csimson5@privacy.gov.au', '1st Floor', '610-639-4990');
insert into customer (id, first_name, last_name, email, address, phone) values (7, 'Herby', 'Jeff', 'hjeff6@usda.gov', 'Suite 40', '572-679-8406');
insert into customer (id, first_name, last_name, email, address, phone) values (8, 'Sandi', 'Wrixon', 'swrixon7@liveinternet.ru', '4th Floor', '622-787-9905');
insert into customer (id, first_name, last_name, email, address, phone) values (9, 'Shanan', 'Mapowder', 'smapowder8@walmart.com', 'Apt 44', '662-326-1654');
insert into customer (id, first_name, last_name, email, address, phone) values (10, 'Paquito', 'Enochsson', 'penochsson9@narod.ru', 'Room 617', '897-183-6498');
insert into customer (id, first_name, last_name, email, address, phone) values (11, 'Torry', 'Pirrie', 'tpirriea@deviantart.com', 'Room 74', '236-237-8991');
insert into customer (id, first_name, last_name, email, address, phone) values (12, 'Colet', 'Knapman', 'cknapmanb@cnbc.com', '17th Floor', '296-665-5831');
insert into customer (id, first_name, last_name, email, address, phone) values (13, 'Nicoline', 'Angric', 'nangricc@narod.ru', 'Suite 15', '475-139-2061');
insert into customer (id, first_name, last_name, email, address, phone) values (14, 'Timofei', 'Thorby', 'tthorbyd@who.int', 'Suite 77', '638-599-4913');
insert into customer (id, first_name, last_name, email, address, phone) values (15, 'Joe', 'Basili', 'jbasilie@last.fm', 'Room 1203', '120-553-7279');
insert into customer (id, first_name, last_name, email, address, phone) values (16, 'Suzanna', 'Southerden', 'ssoutherdenf@artisteer.com', '14th Floor', '320-111-1616');
insert into customer (id, first_name, last_name, email, address, phone) values (17, 'Sibeal', 'Hars', 'sharsg@weebly.com', '12th Floor', '954-305-7411');
insert into customer (id, first_name, last_name, email, address, phone) values (18, 'Barbie', 'Fauguel', 'bfauguelh@hao123.com', 'PO Box 51555', '759-898-9884');
insert into customer (id, first_name, last_name, email, address, phone) values (19, 'Maxie', 'Bowater', 'mbowateri@ifeng.com', 'Apt 1289', '727-456-5394');
insert into customer (id, first_name, last_name, email, address, phone) values (20, 'Edgar', 'Mossop', 'emossopj@prweb.com', 'Suite 10', '443-606-3400');
insert into customer (id, first_name, last_name, email, address, phone) values (21, 'Vite', 'Jesper', 'vjesperk@cnet.com', '1st Floor', '690-999-8059');
insert into customer (id, first_name, last_name, email, address, phone) values (22, 'Tina', 'Megainey', 'tmegaineyl@hhs.gov', 'PO Box 26409', '858-669-4899');
insert into customer (id, first_name, last_name, email, address, phone) values (23, 'Guthry', 'Whild', 'gwhildm@unc.edu', 'Apt 1733', '207-862-2432');
insert into customer (id, first_name, last_name, email, address, phone) values (24, 'Deloris', 'MacTeague', 'dmacteaguen@geocities.com', 'Room 1900', '968-549-5410');
insert into customer (id, first_name, last_name, email, address, phone) values (25, 'Alaric', 'Wallice', 'awalliceo@barnesandnoble.com', 'Room 1188', '755-299-3984');
insert into customer (id, first_name, last_name, email, address, phone) values (26, 'Frasier', 'Hendriks', 'fhendriksp@purevolume.com', '12th Floor', '303-536-7039');
insert into customer (id, first_name, last_name, email, address, phone) values (27, 'Ernest', 'Richel', 'erichelq@blogtalkradio.com', 'Room 1752', '767-979-6315');
insert into customer (id, first_name, last_name, email, address, phone) values (28, 'Liuka', 'Pautard', 'lpautardr@ning.com', 'PO Box 81124', '613-542-2964');
insert into customer (id, first_name, last_name, email, address, phone) values (29, 'Cinderella', 'Gear', 'cgears@umich.edu', 'PO Box 40448', '336-760-9004');
insert into customer (id, first_name, last_name, email, address, phone) values (30, 'Kacey', 'Bread', 'kbreadt@hc360.com', 'Suite 20', '472-947-7527');
insert into customer (id, first_name, last_name, email, address, phone) values (31, 'Mahala', 'Rayer', 'mrayeru@shutterfly.com', 'PO Box 86419', '329-119-2879');
insert into customer (id, first_name, last_name, email, address, phone) values (32, 'Victoir', 'Hesbrook', 'vhesbrookv@unicef.org', '6th Floor', '766-877-1716');
insert into customer (id, first_name, last_name, email, address, phone) values (33, 'Katharina', 'Grogor', 'kgrogorw@auda.org.au', 'Room 1410', '845-207-4602');
insert into customer (id, first_name, last_name, email, address, phone) values (34, 'Cornelius', 'Eaden', 'ceadenx@theguardian.com', '5th Floor', '277-482-5889');
insert into customer (id, first_name, last_name, email, address, phone) values (35, 'Georgeta', 'Slaght', 'gslaghty@nationalgeographic.com', '3rd Floor', '246-268-4354');
insert into customer (id, first_name, last_name, email, address, phone) values (36, 'Constantina', 'Zavattieri', 'czavattieriz@who.int', '4th Floor', '332-417-6266');
insert into customer (id, first_name, last_name, email, address, phone) values (37, 'Demetria', 'Huggill', 'dhuggill10@state.gov', 'PO Box 17289', '812-731-7703');
insert into customer (id, first_name, last_name, email, address, phone) values (38, 'Lilli', 'Ancliffe', 'lancliffe11@slate.com', '6th Floor', '911-860-9036');
insert into customer (id, first_name, last_name, email, address, phone) values (39, 'Jillene', 'Murty', 'jmurty12@google.de', 'Suite 53', '344-564-7636');
insert into customer (id, first_name, last_name, email, address, phone) values (40, 'Terrance', 'Absalom', 'tabsalom13@mediafire.com', 'Apt 1495', '769-604-2820');
insert into customer (id, first_name, last_name, email, address, phone) values (41, 'Magnum', 'Colam', 'mcolam14@facebook.com', '4th Floor', '908-347-5776');
insert into customer (id, first_name, last_name, email, address, phone) values (42, 'Mariel', 'Broome', 'mbroome15@ox.ac.uk', '12th Floor', '158-525-0305');
insert into customer (id, first_name, last_name, email, address, phone) values (43, 'Leanna', 'Bailes', 'lbailes16@wikispaces.com', 'PO Box 98966', '817-752-9264');
insert into customer (id, first_name, last_name, email, address, phone) values (44, 'Bryn', 'Garbett', 'bgarbett17@businessinsider.com', 'Apt 691', '715-197-8642');
insert into customer (id, first_name, last_name, email, address, phone) values (45, 'Katerine', 'Camerati', 'kcamerati18@narod.ru', 'Room 469', '789-431-1300');
insert into customer (id, first_name, last_name, email, address, phone) values (46, 'Joly', 'Sherar', 'jsherar19@archive.org', 'Apt 416', '842-284-1185');
insert into customer (id, first_name, last_name, email, address, phone) values (47, 'Saundra', 'Scrivens', 'sscrivens1a@washingtonpost.com', 'PO Box 58923', '247-439-2303');
insert into customer (id, first_name, last_name, email, address, phone) values (48, 'Humberto', 'Chaperlin', 'hchaperlin1b@google.com', 'Apt 1774', '848-561-7346');
insert into customer (id, first_name, last_name, email, address, phone) values (49, 'Chryste', 'Storck', 'cstorck1c@shareasale.com', 'Suite 8', '137-553-8819');
insert into customer (id, first_name, last_name, email, address, phone) values (50, 'Garreth', 'Harland', 'gharland1d@economist.com', 'Apt 201', '801-176-0369');
SELECT setval('customer_id_seq', (SELECT max(id) FROM customer));
